override: false

cache:
  enable: true

favicon:
  small: /images/favicon.ico
  medium: /images/favicon.ico
  apple_touch_icon: /images/favicon.ico
  safari_pinned_tab: /images/favicon.ico
  android_manifest: /images/manifest.json
  #ms_browserconfig: /images/browserconfig.xml

  
# Set default keywords (Use a comma to separate)
# 站点关键字，利于 SEO 大概，记得用英文逗号分隔
keywords: puppetsheep,博客,灵魂只应独行,hexo 

rss:

footer:
 
  since: 2019

  icon:
    name: heart
  copyright:
  powered:
    enable: false
    version: false

  theme:
    enable: false
    version: false
  beian:
    enable: true
    icp: 浙ICP备17046103号
    
creative_commons:
  license: by-nc-sa
  sidebar: false
  post: false
  
canonical: true

seo: true

index_with_subtitle: false

exturl: false

menu:
  home: / || home
  links: /links || link
  tags: /tags || tags
  categories: /categories || th
  archives: /archives || archive
  about: /about || futbol-o
  comments: /comments || comments

menu_settings:
  icons: true
  badges: false


scheme: Muse
#scheme: Mist
#scheme: Pisces
#scheme: Gemini

site_state: true

social:
  GitHub: https://github.com/puppetsheep || github
  E-Mail: mailto:admin@puppetsheep.cn || envelope
  微博: https://weibo.com/u/6241927108 || weibo
  QQ: http://wpa.qq.com/msgrd?v=3&uin=2209502839&site=qq&menu=yes || qq


social_icons:
  enable: true
  icons_only: false
  transition: false


#links_icon: link
#links_title: 都是大佬
#links_layout: block
#links:



avatar:
  url: /images/QQ.jpg
  rounded: true
  opacity: 1
  rotated: false

toc:
  enable: true
  number: true
  wrap: false
  max_depth: 6

sidebar:
  position: left
  display: hide

  offset: 12
  b2t: false
  scrollpercent: true
  onmobile: true


scroll_to_more: true

save_scroll: false

excerpt_description: false

auto_excerpt:
  enable: false
  length: 300

read_more_btn: true

post_meta:
  item_text: true
  created_at: true
  updated_at:
    enabled: true
    another_day: true
  categories: true

symbols_count_time:
  separated_meta: true
  item_text_post: true
  item_text_total: false
  awl: 4
  wpm: 275

codeblock:
  border_radius: 1
  copy_button:
    enable: true
    show_result: true

reward:
  enable: true
  comment: 打..打..打.....劫！
  wechatpay: /images/wechatpay.png
  alipay: /images/alipay.png
  #bitcoin: /images/bitcoin.jpg


related_posts:
  enable: false
  title: # custom header, leave empty to use the default one
  display_in_home: false
  params:
    maxCount: 5
    #PPMixingRate: 0.0
    #isDate: false
    #isImage: false
    #isExcerpt: false

post_edit:
  enable: false
  url: https://github.com/user-name/repo-name/tree/branch-name/subdirectory-name
  #url: https://github.com/user-name/repo-name/edit/branch-name/subdirectory-name # Link for fork & edit.



disable_baidu_tranformation: false

mobile_layout_economy: false

android_chrome_color: "#222"

custom_logo:
  enabled: false
  image:

highlight_theme: night eighties

cheers_enabled: true


font:
  enable: false

  host:

  global:
    external: true
    family: Lato
    size:

  headings:
    external: true
    family:
    size:

  posts:
    external: true
    family:

  logo:
    external: true
    family:
    size:

  codes:
    external: true
    family:
    size:

math:
  enable: true

  
  per_page: true

  engine: mathjax
  
  mathjax:
  
    cdn: //cdn.jsdelivr.net/npm/mathjax@2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  
  katex:
    cdn: //cdn.jsdelivr.net/npm/katex@0.7.1/dist/katex.min.css
    copy_tex:
      enable: false
      copy_tex_js: //cdn.jsdelivr.net/npm/katex@0/dist/contrib/copy-tex.min.js
      copy_tex_css: //cdn.jsdelivr.net/npm/katex@0/dist/contrib/copy-tex.min.css


pdf:
  enable: false

  per_page: true

  height: 500px

  pdfobject:
    
    cdn: //cdn.jsdelivr.net/npm/pdfobject@2.1.1/pdfobject.min.js
    #cdn: //cdnjs.cloudflare.com/ajax/libs/pdfobject/2.1.1/pdfobject.min.js

han: false

pangu: false

hitalk: 
  enable: true
  appid: hJPpM0TnxOmSBsMOu9wRznwt-gzGzoHsz
  appkey: tihJEkxw0pNdrWQbhnyyo0oA
  placeholder: 不吐槽一下嘛~
  avatar: wavatar
  guest_info: nick,mail,link

needmoreshare2:
  enable: false
  postbottom:
    enable: false
    options:
      iconStyle: box
      boxForm: horizontal
      position: bottomCenter
      networks: Weibo,Wechat,Douban,QQZone,Twitter,Facebook
  float:
    enable: false
    options:
      iconStyle: box
      boxForm: horizontal
      position: middleRight
      networks: Weibo,Wechat,Douban,QQZone,Twitter,Facebook


rating:
  enable: false
  id:     #<app_id>
  color:  fc6423
  
leancloud_visitors:
  enable: false
  app_id: 
  app_key: 
  security: true
  betterPerformance: false

firestore:
  enable: false
  collection: articles #required, a string collection name to access firestore database
  apiKey: #required
  projectId: #required
  bluebird: false #enable this if you want to include bluebird 3.5.1(core version) Promise polyfill

busuanzi_count:
  enable: false
  total_visitors: true
  total_visitors_icon: user
  total_views: true
  total_views_icon: eye
  post_views: true
  post_views_icon: eye


baidu_push: false

calendar:
  enable: false
  calendar_id: <required> # Your Google account E-Mail
  api_key: <required>
  orderBy: startTime
  offsetMax: 24 # Time Range
  offsetMin: 4 # Time Range
  showDeleted: false
  singleEvents: true
  maxResults: 250

algolia_search:
  enable: false
  hits:
    per_page: 10
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}"
    hits_stats: "${hits} results found in ${time} ms"

local_search:
  enable: true
  trigger: auto
  top_n_per_article: 1
  unescape: false

search:
     path: search.xml
     field: post
     format: html
     limit: 10000

bookmark:
  enable: false
  save: auto


note:

  style: flat
  icons: true
  border_radius: 3
  light_bg_offset: 0

label: true

tabs:
  enable: true
  transition:
    tabs: true
    labels: true
  border_radius: 0

reading_progress:
  enable: false
  color: "#37c6c0"
  height: 2px


motion:
  enable: true
  async: true
  transition:
    post_block: fadeIn
    post_header: slideDownIn
    post_body: slideDownIn
    coll_header: slideLeftIn
    # Only for Pisces | Gemini.
    sidebar: slideUpIn


fancybox: true


fastclick: false


lazyload: false


pace: false

pace_theme: pace-theme-minimal


vendors:
  _internal: lib

  jquery: //cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js

  fancybox: https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.js
  fancybox_css: https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.css

  fastclick: //cdn.jsdelivr.net/npm/fastclick@1/lib/fastclick.min.js
  # fastclick: //cdnjs.cloudflare.com/ajax/libs/fastclick/1.0.6/fastclick.min.js

  lazyload: //cdn.jsdelivr.net/npm/jquery-lazyload@1/jquery.lazyload.min.js
  # lazyload: //cdnjs.cloudflare.com/ajax/libs/jquery_lazyload/1.9.7/jquery.lazyload.min.js

  velocity: //cdn.jsdelivr.net/npm/velocity-animate@1/velocity.min.js
  # velocity: //cdnjs.cloudflare.com/ajax/libs/velocity/1.2.1/velocity.min.js
  velocity_ui: //cdn.jsdelivr.net/npm/velocity-animate@1/velocity.ui.min.js
  # velocity_ui: //cdnjs.cloudflare.com/ajax/libs/velocity/1.2.1/velocity.ui.min.js


  ua_parser: //cdn.jsdelivr.net/npm/ua-parser-js@0/src/ua-parser.min.js
  # ua_parser: //cdnjs.cloudflare.com/ajax/libs/UAParser.js/0.7.9/ua-parser.min.js

  fontawesome: //cdn.jsdelivr.net/npm/font-awesome@4/css/font-awesome.min.css
  # fontawesome: //cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.2/css/font-awesome.min.css

  algolia_instant_js: //cdn.jsdelivr.net/npm/instantsearch.js@2/dist/instantsearch.js
  algolia_instant_css: //cdn.jsdelivr.net/npm/instantsearch.js@2/dist/instantsearch.min.css



  pace: //cdn.jsdelivr.net/npm/pace-js@1/pace.min.js
  # pace: //cdnjs.cloudflare.com/ajax/libs/pace/1.0.2/pace.min.js
  pace_css: //cdn.jsdelivr.net/npm/pace-js@1/themes/blue/pace-theme-minimal.css
  # pace_css: //cdnjs.cloudflare.com/ajax/libs/pace/1.0.2/themes/blue/pace-theme-minimal.min.css


  canvas_nest: //cdn.jsdelivr.net/gh/theme-next/theme-next-canvas-nest@1/canvas-nest.min.js
  canvas_nest_nomobile: //cdn.jsdelivr.net/gh/theme-next/theme-next-canvas-nest@1/canvas-nest-nomobile.min.js


  # three: //cdn.jsdelivr.net/gh/theme-next/theme-next-three@1/three.min.js
  # three_waves: //cdn.jsdelivr.net/gh/theme-next/theme-next-three@1/three-waves.min.js
  # canvas_lines: //cdn.jsdelivr.net/gh/theme-next/theme-next-three@1/canvas_lines.min.js
  # canvas_sphere: //cdn.jsdelivr.net/gh/theme-next/theme-next-three@1/canvas_sphere.min.js
  three:
  three_waves:
  canvas_lines:
  canvas_sphere:

  # canvas_ribbon: //cdn.jsdelivr.net/gh/theme-next/theme-next-canvas-ribbon@1/canvas-ribbon.js
  canvas_ribbon:

  # han: //cdn.jsdelivr.net/npm/han-css@3/dist/han.min.css
  # han: //cdnjs.cloudflare.com/ajax/libs/Han/3.3.0/han.min.css
  han:


  # pangu: //cdn.jsdelivr.net/npm/pangu@3/dist/browser/pangu.min.js
  # pangu: //cdnjs.cloudflare.com/ajax/libs/pangu/3.3.0/pangu.min.js
  pangu:


  # needmoreshare2_js: //cdn.jsdelivr.net/gh/theme-next/theme-next-needmoreshare2@1/needsharebutton.min.js
  # needmoreshare2_css: //cdn.jsdelivr.net/gh/theme-next/theme-next-needmoreshare2@1/needsharebutton.min.css
  needmoreshare2_js:
  needmoreshare2_css:


  bookmark: //cdn.jsdelivr.net/gh/theme-next/theme-next-bookmark@1/bookmark.min.js


  reading_progress: //cdn.jsdelivr.net/gh/theme-next/theme-next-reading-progress@1/reading_progress.min.js


  leancloud: //cdn.jsdelivr.net/npm/leancloud-storage@3/dist/av-min.js



  valine: //cdn.jsdelivr.net/npm/valine@1/dist/Valine.min.js
  # valine: //cdnjs.cloudflare.com/ajax/libs/valine/1.3.4/Valine.min.js


  # js-md5
  # See: https://github.com/emn178/js-md5
  # Example:
  # md5: //cdn.jsdelivr.net/npm/js-md5@0/src/md5.min.js
  md5:

# Assets
css: css
js: js
images: images
